global using BuildingBlocks.Application.Authorization;
global using Search.Domain.Constants;
global using Search.Domain.Documents;
global using Search.Application.Interfaces;
global using Search.Infrastructure.Services;
global using Search.Domain.Models;
global using Search.Infrastructure.Extensions.DependencyInjection;
global using BuildingBlocks.Application.Abstractions;
global using Result = BuildingBlocks.Application.Abstractions.Result;
global using MassTransit;
global using Microsoft.EntityFrameworkCore;
