
sonar.projectKey=auction-platform-microservices
sonar.organization=your-organization

sonar.projectName=Auction Platform Microservices
sonar.projectVersion=1.0.0

sonar.sources=src/
sonar.tests=tests/
sonar.sourceEncoding=UTF-8

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx

sonar.exclusions=\
  **/Migrations/**,\
  **/wwwroot/**,\
  **/node_modules/**,\
  **/bin/**,\
  **/obj/**,\
  **/*.Designer.cs,\
  **/web/**

sonar.coverage.exclusions=\
  **/Migrations/**,\
  **/Tests/**,\
  **/*.Designer.cs,\
  **/Program.cs,\
  **/Startup.cs,\
  **/HostingExtensions.cs

sonar.cpd.exclusions=\
  **/Migrations/**,\
  **/Contracts/**,\
  **/*Dto.cs,\
  **/*Request.cs,\
  **/*Response.cs

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300


sonar.pullrequest.provider=github

sonar.issue.ignore.multicriteria=e1,e2,e3

sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S4144
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*Dto.cs

sonar.issue.ignore.multicriteria.e2.ruleKey=csharpsquid:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/Program.cs

sonar.issue.ignore.multicriteria.e3.ruleKey=csharpsquid:S1135
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*
