<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Search.Application\Search.Application.csproj" />
    <ProjectReference Include="..\Search.Domain\Search.Domain.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Common.Contracts\Common.Contracts.csproj" />
    <ProjectReference Include="..\..\Auction\Auction.Contracts\AuctionService.Contracts.csproj" />
    <ProjectReference Include="..\..\Bidding\Bidding.Contracts\BidService.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
