export const TIME_CONSTANTS = {
  MILLISECONDS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_WEEK: 7,
  DAYS_PER_MONTH: 30,
  DAYS_PER_YEAR: 365,
} as const

export const MILLISECONDS_PER_MINUTE = TIME_CONSTANTS.MILLISECONDS_PER_SECOND * TIME_CONSTANTS.SECONDS_PER_MINUTE
export const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTE * TIME_CONSTANTS.MINUTES_PER_HOUR
export const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * TIME_CONSTANTS.HOURS_PER_DAY
