global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auction-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auction-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'auction-service'

  - job_name: 'bid-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bid-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'bid-service'

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'payment-service'

  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'notification-service'

  - job_name: 'identity-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['identity-service:5001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'identity-service'

  - job_name: 'utility-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['utility-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'utility-service'

  - job_name: 'gateway-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'gateway-service'

  - job_name: 'storage-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'storage-service'
