@AuctionService.API_HostAddress = http://localhost:7001

### Get all auctions
GET {{AuctionService.API_HostAddress}}/api/auctions
Accept: application/json

###

### Get auction by ID
GET {{AuctionService.API_HostAddress}}/api/auctions/{{auctionId}}
Accept: application/json

###

### Create new auction
POST {{AuctionService.API_HostAddress}}/api/auctions
Content-Type: application/json

{
  "title": "2024 Tesla Model 3",
  "description": "Electric sedan in excellent condition",
  "startingPrice": 35000
}

###

### Update auction
PUT {{AuctionService.API_HostAddress}}/api/auctions/{{auctionId}}
Content-Type: application/json

{
  "title": "Updated Title",
  "description": "Updated description"
}

###

### Delete auction
DELETE {{AuctionService.API_HostAddress}}/api/auctions/{{auctionId}}

###
