<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference>
    <ProjectReference Include="../../Orchestration.Sagas/Orchestration.Sagas.csproj" />
  </ItemGroup>
</Project>
