global using BuildingBlocks.Application.Abstractions;
global using BuildingBlocks.Application.Abstractions.Messaging;
global using BuildingBlocks.Application.Abstractions.Providers;
global using BuildingBlocks.Application.CQRS.Commands;
global using BuildingBlocks.Application.CQRS.Queries;
global using Microsoft.Extensions.Logging;
global using Jobs.Application.DTOs;
global using Jobs.Application.Interfaces;
global using Jobs.Domain.Constants;
global using Job = Jobs.Domain.Entities.Job;
global using JobStatus = Jobs.Domain.Enums.JobStatus;
