apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-azure-and-external-integrations
  namespace: auction-platform
spec:
  podSelector:
    matchLabels:
      tier: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 10000
        - protocol: TCP
          port: 587
